/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author sidac
 */
public class testLogFrame extends javax.swing.JFrame {

    /**
     * Creates new form testLogFrame
     */
    public testLogFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dateValueLabel = new javax.swing.JLabel();
        contentWrapper = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextArea();
        amountValueLabel = new javax.swing.JTextField();
        addDataBtn = new javax.swing.JButton();
        nextDateBtn = new javax.swing.JButton();
        previousDateBtn = new javax.swing.JButton();
        totalInDayLabel = new javax.swing.JLabel();
        totalInDayValueLabel = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Ngày:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 29, 14);

        dateValueLabel.setText("jLabel2");
        jPanel1.add(dateValueLabel);
        dateValueLabel.setBounds(50, 10, 34, 14);

        contentWrapper.setLayout(null);

        descriptionText.setColumns(20);
        descriptionText.setRows(5);
        jScrollPane1.setViewportView(descriptionText);

        contentWrapper.add(jScrollPane1);
        jScrollPane1.setBounds(30, 10, 130, 70);

        amountValueLabel.setText("jTextField1");
        contentWrapper.add(amountValueLabel);
        amountValueLabel.setBounds(30, 90, 60, 20);

        addDataBtn.setText("Thêm");
        addDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataBtnActionPerformed(evt);
            }
        });
        contentWrapper.add(addDataBtn);
        addDataBtn.setBounds(70, 110, 59, 23);

        jPanel1.add(contentWrapper);
        contentWrapper.setBounds(30, 50, 200, 140);

        nextDateBtn.setText("jButton1");
        jPanel1.add(nextDateBtn);
        nextDateBtn.setBounds(100, 0, 20, 23);

        previousDateBtn.setText("jButton2");
        jPanel1.add(previousDateBtn);
        previousDateBtn.setBounds(100, 20, 20, 23);

        totalInDayLabel.setText("Tổng:");
        jPanel1.add(totalInDayLabel);
        totalInDayLabel.setBounds(150, 10, 28, 14);

        totalInDayValueLabel.setText("jLabel3");
        jPanel1.add(totalInDayValueLabel);
        totalInDayValueLabel.setBounds(190, 10, 34, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 40, 250, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDataBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDataBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testLogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testLogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testLogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testLogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testLogFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDataBtn;
    private javax.swing.JTextField amountValueLabel;
    private javax.swing.JPanel contentWrapper;
    private javax.swing.JLabel dateValueLabel;
    private javax.swing.JTextArea descriptionText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextDateBtn;
    private javax.swing.JButton previousDateBtn;
    private javax.swing.JLabel totalInDayLabel;
    private javax.swing.JLabel totalInDayValueLabel;
    // End of variables declaration//GEN-END:variables
}
