/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author sidac
 */
public class testLogFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form testLogFrame
     */
    public testLogFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dateValueLabel = new javax.swing.JLabel();
        contentWrapper = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextArea();
        amountValueLabel = new javax.swing.JTextField();
        addDataBtn = new javax.swing.JButton();
        typeCombox = new javax.swing.JComboBox<>();
        nextDateBtn = new javax.swing.JButton();
        previousDateBtn = new javax.swing.JButton();
        totalInDayLabel = new javax.swing.JLabel();
        totalInDayValueLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        logTable = new javax.swing.JTable();
        deleteBtn = new javax.swing.JButton();
        backActionBtn = new javax.swing.JButton();
        nextActionBtn = new javax.swing.JButton();
        dateChooserLabel = new javax.swing.JLabel();
        fromDateValueLabel = new javax.swing.JTextField();
        toDateValueLabel = new javax.swing.JTextField();
        totalRowCountLabel = new javax.swing.JLabel();
        amounChoosertLabel = new javax.swing.JLabel();
        fromAmountValueLabel = new javax.swing.JTextField();
        toAmountValueLabel = new javax.swing.JTextField();
        filterActionBtn = new javax.swing.JButton();
        sortBtn = new javax.swing.JButton();
        typeChooserCombox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        itemTypeLabel = new javax.swing.JLabel();
        typeOfSortValueBtn = new javax.swing.JButton();
        testText = new javax.swing.JLabel();
        typeChooserCom = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Ngày:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-1, 4, 40, 20);

        dateValueLabel.setText("jLabel2");
        jPanel1.add(dateValueLabel);
        dateValueLabel.setBounds(44, 4, 50, 20);

        contentWrapper.setLayout(null);

        descriptionText.setColumns(20);
        descriptionText.setRows(5);
        jScrollPane1.setViewportView(descriptionText);

        contentWrapper.add(jScrollPane1);
        jScrollPane1.setBounds(30, 10, 150, 80);

        amountValueLabel.setText("jTextField1");
        contentWrapper.add(amountValueLabel);
        amountValueLabel.setBounds(30, 90, 60, 20);

        addDataBtn.setText("Thêm");
        addDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataBtnActionPerformed(evt);
            }
        });
        contentWrapper.add(addDataBtn);
        addDataBtn.setBounds(70, 110, 59, 23);

        typeCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        contentWrapper.add(typeCombox);
        typeCombox.setBounds(120, 90, 57, 20);

        jPanel1.add(contentWrapper);
        contentWrapper.setBounds(30, 50, 200, 140);

        nextDateBtn.setText("jButton1");
        nextDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextDateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(nextDateBtn);
        nextDateBtn.setBounds(100, 0, 20, 23);

        previousDateBtn.setText("jButton2");
        previousDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousDateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(previousDateBtn);
        previousDateBtn.setBounds(100, 20, 20, 23);

        totalInDayLabel.setText("Tổng:");
        jPanel1.add(totalInDayLabel);
        totalInDayLabel.setBounds(148, 4, 30, 20);

        totalInDayValueLabel.setText("jLabel3");
        totalInDayValueLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalInDayValueLabelMouseClicked(evt);
            }
        });
        jPanel1.add(totalInDayValueLabel);
        totalInDayValueLabel.setBounds(190, 4, 40, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 40, 260, 210);

        logTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Mục", "Số tiền", "Ghi chú", "Loại"
            }
        ));
        jScrollPane2.setViewportView(logTable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(330, 50, 360, 120);

        deleteBtn.setText("Xóa");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn);
        deleteBtn.setBounds(330, 200, 51, 23);

        backActionBtn.setText("<");
        backActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backActionBtn);
        backActionBtn.setBounds(330, 30, 41, 23);

        nextActionBtn.setText(">");
        nextActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nextActionBtn);
        nextActionBtn.setBounds(370, 30, 41, 23);

        dateChooserLabel.setText("Ngày:");
        getContentPane().add(dateChooserLabel);
        dateChooserLabel.setBounds(410, 190, 40, 14);

        fromDateValueLabel.setText("jTextField1");
        getContentPane().add(fromDateValueLabel);
        fromDateValueLabel.setBounds(460, 190, 90, 20);

        toDateValueLabel.setText("jTextField2");
        getContentPane().add(toDateValueLabel);
        toDateValueLabel.setBounds(590, 190, 90, 20);

        totalRowCountLabel.setText("jLabel3");
        getContentPane().add(totalRowCountLabel);
        totalRowCountLabel.setBounds(650, 30, 34, 14);

        amounChoosertLabel.setText("Số tiền: ");
        getContentPane().add(amounChoosertLabel);
        amounChoosertLabel.setBounds(410, 230, 50, 14);

        fromAmountValueLabel.setText("jTextField1");
        fromAmountValueLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fromAmountValueLabelFocusLost(evt);
            }
        });
        fromAmountValueLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromAmountValueLabelActionPerformed(evt);
            }
        });
        getContentPane().add(fromAmountValueLabel);
        fromAmountValueLabel.setBounds(460, 230, 90, 20);

        toAmountValueLabel.setText("jTextField2");
        getContentPane().add(toAmountValueLabel);
        toAmountValueLabel.setBounds(590, 230, 90, 20);

        filterActionBtn.setText("Lọc");
        filterActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionBtnActionPerformed(evt);
            }
        });
        getContentPane().add(filterActionBtn);
        filterActionBtn.setBounds(330, 230, 50, 23);

        sortBtn.setText("Sắp xếp");
        sortBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortBtnActionPerformed(evt);
            }
        });
        getContentPane().add(sortBtn);
        sortBtn.setBounds(310, 260, 80, 23);

        typeChooserCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        typeChooserCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeChooserComboxActionPerformed(evt);
            }
        });
        getContentPane().add(typeChooserCombox);
        typeChooserCombox.setBounds(460, 260, 57, 20);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(670, 50, 34, 14);

        itemTypeLabel.setText("Mục:");
        getContentPane().add(itemTypeLabel);
        itemTypeLabel.setBounds(410, 260, 23, 14);

        typeOfSortValueBtn.setText("A-Z");
        typeOfSortValueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeOfSortValueBtnActionPerformed(evt);
            }
        });
        getContentPane().add(typeOfSortValueBtn);
        typeOfSortValueBtn.setBounds(590, 260, 50, 23);

        testText.setText("jLabel2");
        getContentPane().add(testText);
        testText.setBounds(730, 30, 110, 14);

        typeChooserCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(typeChooserCom);
        typeChooserCom.setBounds(720, 190, 57, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDataBtnActionPerformed
        String note = this.descriptionText.getText();
        int amount = Integer.parseInt(this.amountValueLabel.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_addDataBtnActionPerformed

    private void nextDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextDateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextDateBtnActionPerformed

    private void previousDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousDateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previousDateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void backActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionBtnActionPerformed

    private void nextActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextActionBtnActionPerformed

    private void fromAmountValueLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromAmountValueLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromAmountValueLabelActionPerformed

    private void typeChooserComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeChooserComboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeChooserComboxActionPerformed

    private void filterActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterActionBtnActionPerformed

    private void sortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortBtnActionPerformed

    private void typeOfSortValueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeOfSortValueBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeOfSortValueBtnActionPerformed

    private void totalInDayValueLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalInDayValueLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_totalInDayValueLabelMouseClicked

    private void fromAmountValueLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fromAmountValueLabelFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fromAmountValueLabelFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testLogFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testLogFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testLogFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testLogFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testLogFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDataBtn;
    private javax.swing.JLabel amounChoosertLabel;
    private javax.swing.JTextField amountValueLabel;
    private javax.swing.JButton backActionBtn;
    private javax.swing.JPanel contentWrapper;
    private javax.swing.JLabel dateChooserLabel;
    private javax.swing.JLabel dateValueLabel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextArea descriptionText;
    private javax.swing.JButton filterActionBtn;
    private javax.swing.JTextField fromAmountValueLabel;
    private javax.swing.JTextField fromDateValueLabel;
    private javax.swing.JLabel itemTypeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable logTable;
    private javax.swing.JButton nextActionBtn;
    private javax.swing.JButton nextDateBtn;
    private javax.swing.JButton previousDateBtn;
    private javax.swing.JButton sortBtn;
    private javax.swing.JLabel testText;
    private javax.swing.JTextField toAmountValueLabel;
    private javax.swing.JTextField toDateValueLabel;
    private javax.swing.JLabel totalInDayLabel;
    private javax.swing.JLabel totalInDayValueLabel;
    private javax.swing.JLabel totalRowCountLabel;
    private javax.swing.JComboBox<String> typeChooserCom;
    private javax.swing.JComboBox<String> typeChooserCombox;
    private javax.swing.JComboBox<String> typeCombox;
    private javax.swing.JButton typeOfSortValueBtn;
    // End of variables declaration//GEN-END:variables
}
